import { MainFooter } from "@/components/core/main-footer";
import { MainHeader } from "@/components/core/main-header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className={`bg-gray-100 m-0 ${
            process.env.REACT_APP_ENV === "test"
              ? "ring-2 ring-inset ring-red-500 rounded-lg"
              : ""
          }`}
        >
          <div className="flex flex-col min-h-screen lg:container mx-auto px-4 h-full">
            <div className={"grow flex flex-col"}>
              <MainHeader />
              <div className={"grow flex flex-col"}>
                {/* TODO: navigation */}
                <main className="grow flex flex-col sm:ml-12 lg:ml-14">
                  {children}
                </main>
              </div>
            </div>
            <MainFooter />
          </div>
          {/* TODO: navigation */}
        </div>
      </body>
    </html>
  );
}
